// Grocery Data
export const groceryCategories = [
  "Baking & Cooking Materials",
  "Meal-Prepped Goods",
  "Snacks",
  "Proteins",
  "Produce",
  "Dairy & Eggs",
  "Pantry Staples",
  "Bakery & Bread",
  "Beverages",
  "Breakfast",
  "Frozen Foods",
  "Condiments & Sauces",
  "Canned & Packaged Goods"
];

export type Grocery = {
  id: string;
  name: string;
  category: string;
  price: number;
  image: string;
  dietaryTags: string[];
  description: string;
};

export const groceries: Grocery[] = [
  // Baking & Cooking Materials
  {
    id: "g101",
    name: "MadeGood Granola Bars",
    category: "Snacks",
    price: 4.99,
    image: "🍫",
    dietaryTags: ["gluten-free", "top-9-allergen-free", "vegan"],
    description: "Organic granola bars produced in a dedicated nut-free facility and free from the Top 9 allergens.",
  },

  {
    id: "g102",
    name: "Enjoy Life Chocolate Chips",
    category: "Baking & Cooking Materials",
    price: 7.49,
    image: "🍫",
    dietaryTags: ["gluten-free", "dairy-free", "top-14-allergen-free", "vegan"],
    description: "Allergy-friendly baking chocolate made without the top 14 allergens in a dedicated facility.",
  },

  {
    id: "g103",
    name: "Schär Artisan White Bread",
    category: "Bakery & Bread",
    price: 6.99,
    image: "🍞",
    dietaryTags: ["gluten-free", "wheat-free"],
    description: "Certified gluten-free sandwich bread that's widely available in major grocery stores.",
  },

  {
    id: "g104",
    name: "Feel Good Foods Chicken Potstickers",
    category: "Frozen Foods",
    price: 8.99,
    image: "🥟",
    dietaryTags: ["gluten-free"],
    description: "Certified gluten-free frozen chicken potstickers made with gluten-free wrappers.",
  },

  {
    id: "g105",
    name: "Simple Mills Almond Flour Crackers",
    category: "Snacks",
    price: 5.99,
    image: "🧀",
    dietaryTags: ["gluten-free", "tree-nut"],
    description: "Gluten-free almond flour crackers made with simple ingredients. Contains almonds.",
  },

  {
    id: "g106",
    name: "Partake Crunchy Cookies",
    category: "Snacks",
    price: 5.49,
    image: "🍪",
    dietaryTags: ["gluten-free", "top-9-allergen-free", "vegan"],
    description: "School-safe cookies free from the Top 9 allergens and certified gluten-free.",
  },

  {
    id: "g107",
    name: "Katz Glazed Donuts",
    category: "Bakery & Bread",
    price: 6.99,
    image: "🍩",
    dietaryTags: ["gluten-free", "dairy-free", "nut-free"],
    description: "Frozen gluten-free donuts made in a dedicated gluten-free and nut-free facility.",
  },

  {
    id: "g108",
    name: "Bob's Red Mill Gluten Free Oats",
    category: "Breakfast",
    price: 7.49,
    image: "🥣",
    dietaryTags: ["gluten-free", "whole-grain"],
    description: "Whole grain rolled oats that are processed and tested to meet gluten-free standards.",
  }];

// export const recipes: Recipe[] = [
//   {
//     id: "r1",
//     name: "Grilled Chicken with Roasted Vegetables",
//     image: "🍗",
//     cookTime: 30,
//     servings: 4,
//     difficulty: "Easy",
//     dietaryTags: ["paleo", "keto", "high-protein", "gluten-free"],
//     ingredients: ["Chicken breast", "Broccoli", "Bell peppers", "Olive oil"],
//     description: "Simple and delicious grilled chicken with seasonal vegetables",
//   },
//   {
//     id: "r2",
//     name: "Quinoa Buddha Bowl",
//     image: "🥣",
//     cookTime: 20,
//     servings: 2,
//     difficulty: "Easy",
//     dietaryTags: ["vegan", "vegetarian", "gluten-free"],
//     ingredients: [
//       "Quinoa",
//       "Chickpeas",
//       "Spinach",
//       "Avocado",
//       "Tahini",
//       "Lemon",
//     ],
//     description: "Nutritious and colorful bowl packed with plant-based protein",
//   },
//   {
//     id: "r3",
//     name: "Salmon with Asparagus",
//     image: "🐟",
//     cookTime: 25,
//     servings: 2,
//     difficulty: "Easy",
//     dietaryTags: ["fish", "paleo", "high-protein", "gluten-free"],
//     ingredients: ["Salmon fillet", "Asparagus", "Lemon", "Garlic", "Olive oil"],
//     description: "Omega-3 rich salmon with tender roasted asparagus",
//   },
//   {
//     id: "r4",
//     name: "Veggie Stir Fry",
//     image: "🥦",
//     cookTime: 20,
//     servings: 3,
//     difficulty: "Easy",
//     dietaryTags: ["vegan", "vegetarian", "gluten-free"],
//     ingredients: [
//       "Broccoli",
//       "Bell peppers",
//       "Snap peas",
//       "Soy sauce",
//       "Ginger",
//       "Garlic",
//     ],
//     description: "Quick and colorful vegetable stir fry with ginger and garlic",
//   },
//   {
//     id: "r5",
//     name: "Almond Flour Pancakes",
//     image: "🥞",
//     cookTime: 20,
//     servings: 2,
//     difficulty: "Easy",
//     dietaryTags: ["keto", "gluten-free", "tree-nut"],
//     ingredients: ["Almond flour", "Eggs", "Honey", "Vanilla"],
//     description: "Low-carb and gluten-free pancakes perfect for breakfast",
//   },
//   {
//     id: "r6",
//     name: "Mediterranean Chickpea Salad",
//     image: "🥗",
//     cookTime: 15,
//     servings: 4,
//     difficulty: "Easy",
//     dietaryTags: ["vegan", "vegetarian", "mediterranean", "gluten-free"],
//     ingredients: [
//       "Chickpeas",
//       "Cucumber",
//       "Tomato",
//       "Red onion",
//       "Feta",
//       "Olive oil",
//     ],
//     description: "Fresh and healthy salad with a Mediterranean twist",
//   },
//   {
//     id: "r7",
//     name: "Thai Coconut Curry",
//     image: "🍛",
//     cookTime: 35,
//     servings: 4,
//     difficulty: "Medium",
//     dietaryTags: ["vegan", "vegetarian", "gluten-free"],
//     ingredients: [
//       "Coconut milk",
//       "Curry paste",
//       "Vegetables",
//       "Tofu",
//       "Lime",
//       "Rice",
//     ],
//     description: "Creamy and aromatic Thai curry with vegetables",
//   },
//   {
//     id: "r8",
//     name: "Protein Energy Balls",
//     image: "🍫",
//     cookTime: 15,
//     servings: 12,
//     difficulty: "Easy",
//     dietaryTags: ["vegan", "vegetarian", "keto"],
//     ingredients: ["Protein powder", "Almond butter", "Dark chocolate", "Oats"],
//     description: "No-bake energy balls perfect for a quick snack",
//   },
//   {
//     id: "r9",
//     name: "Zucchini Noodles with Pesto",
//     image: "🍝",
//     cookTime: 20,
//     servings: 2,
//     difficulty: "Easy",
//     dietaryTags: ["vegan", "vegetarian", "gluten-free", "low-carb"],
//     ingredients: ["Zucchini", "Basil", "Garlic", "Olive oil", "Pine nuts"],
//     description: "Light and healthy spiralized zucchini with fresh pesto",
//   },
//   {
//     id: "r10",
//     name: "Slow Cooker Vegetable Soup",
//     image: "🍲",
//     cookTime: 480,
//     servings: 6,
//     difficulty: "Easy",
//     dietaryTags: ["vegan", "vegetarian", "gluten-free"],
//     ingredients: [
//       "Mixed vegetables",
//       "Vegetable broth",
//       "Tomatoes",
//       "Beans",
//       "Herbs",
//     ],
//     description: "Hearty and comforting vegetable soup made in a slow cooker",
//   },
// ];

// Dining Data
export const diningCategories = [
  "College Campuses",
  "Bakeries",
  "Cafes",
  "Fine Dining",
  "Casual",
  "Food Trucks",
  "Ethnic Cuisine",
];

export type DiningArea = {
  id: string;
  name: string;
  category: string;
  image: string;
  rating: number;
  dietaryTags: string[];
  address: string;
  description: string;
  hours: string;
};

export const diningAreas: DiningArea[] = [
  {
    id: "d1",
    name: "Modern Bread & Bagel",
    category: "Bakeries",
    image: "🥯",
    rating: 4.0,
    dietaryTags: ["vegetarian", "vegan", "gluten-free"],
    address: "472 Columbus Ave",
    description:
      "100% dedicated GF + Top 9 free bakery and café. 4 NYC locations. Uses GF oats — confirm if oat-sensitive",
    hours: "7 AM - 9 PM",
  },
  {
    id: "d2",
    name: "Two Fields Bakeshop",
    category: "Bakeries",
    image: "🥐",
    rating: 4.9,
    dietaryTags: ["gluten-free", "vegetarian"],
    address: "234 Closter Dock Rd",
    description: "Dedicated GF, nut-free, sesame-free bakeshop. School-safe. Entire facility free of gluten and all nuts",
    hours: "8 AM - 10 PM",
  },
  {
    id: "d3",
    name: "Artisan Bakery",
    category: "Bakeries",
    image: "🥐",
    rating: 4.8,
    dietaryTags: ["vegetarian"],
    address: "789 Main St",
    description: "Fresh-baked pastries and bread made daily. Uses GF oats — confirm if oat-sensitive.",
    hours: "7 AM - 6 PM",
  },
  {
    id: "d4",
    name: "HaleLife Bakery",
    category: "Bakeries",
    image: "🍞",
    rating: 4.6,
    dietaryTags: ["gluten-free", "vegetarian", "vegan"],
    address: "2971 Alternate 19 N",
    description: "GF, vegan, free of dairy, egg, soy, peanut, tree nut (except coconut). 4 FL locations. Coconut used throughout.",
    hours: "8 AM - 5 PM",
  },
  {
    id: "d5",
    name: "Erin McKenna''s Bakery",
    category: "Bakeries",
    image: "☕",
    rating: 4.5,
    dietaryTags: ["gluten-free", "soy-free", "vegan"],
    address: "🍩",
    description: "GF, soy-free, vegan, peanut+tree nut free",
    hours: "6 AM - 8 PM",
  },
  {
    id: "d6",
    name: "The Green Leaf Cafe",
    category: "Cafes",
    image: "🌿",
    rating: 4.7,
    dietaryTags: ["vegan", "vegetarian", "gluten-free"],
    address: "888 Green St",
    description: "Organic cafe focusing on sustainable and healthy options",
    hours: "7 AM - 9 PM",
  },
  {
    id: "d7",
    name: "Difference Baker",
    category: "Bakery",
    image: "🍽️",
    rating: 4.9,
    dietaryTags: ["soy-free", "tree nut-free", "gluten-free"],
    address: "42211 Evangelical Ct",
    description: "Born from family allergy experience",
    hours: "5 PM - 11 PM",
  },
  {
    id: "d9",
    name: "Mellow Mushroom",
    category: "Casual",
    image: "🍕",
    rating: 4.3,
    dietaryTags: ["gluten-free"],
    address: "317 Main St Ste 100",
    description: "Casual pizza restaurant with gluten-free options",
    hours: "11 AM - 10 PM",
  },
  {
    id: "d10",
    name: "Disco Chicken & Donuts",
    category: "Casual",
    image: "🍩",
    rating: 4.6,
    dietaryTags: ["vegetarian", "vegan", "gluten-free"],
    address: "Kern's Bakery",
    description: "One of the best gluten-free restaurants in Knoxville",
    hours: "11 AM - 9 PM",
  },
  {
    id: "d11",
    name: "Panda Express",
    category: "Casual",
    image: "🍙",
    rating: 4.5,
    dietaryTags: ["fish", "high-protein"],
    address: "Park Street",
    description: "Fresh poke bowls and sushi from a food truck",
    hours: "12 PM - 9 PM",
  },
  {
    id: "d12",
    name: "CAVA",
    category: "Ethnic Cuisine",
    image: "🫒",
    rating: 4.6,
    dietaryTags: ["mediterranean", "vegan", "vegetarian"],
    address: "666 Mediterranean Ave",
    description: "Mediterranean cuisine with fresh seafood and vegetables",
    hours: "12 PM - 10 PM",
  },
  {
    id: "d13",
    name: "Gluten Free Goose",
    category: "Bakeries",
    image: "🧁",
    rating: 4.9,
    dietaryTags: ["gluten-free", "celiac-safe"],
    address: "6601 Sugar Valley Dr #115, Nashville, TN",
    description: "100% dedicated gluten-free bakery serving breads, pastries, cookies, cakes, and seasonal desserts. Celiac-friendly.",
    hours: "Thu-Sat 7 AM - 1 PM",
  },

  {
    id: "d14",
    name: "Sunflower Bakehouse",
    category: "Bakeries",
    image: "🧁",
    rating: 4.8,
    dietaryTags: ["gluten-free", "vegan", "dairy-free"],
    address: "2414 Lebanon Pike, Nashville, TN",
    description: "Dedicated vegan and gluten-free bakery offering cupcakes, muffins, breakfast, sandwiches, and coffee. Many allergy-friendly options.",
    hours: "Mon-Fri 8 AM - 9 PM, Sat 9 AM - 9 PM, Sun 9 AM - 3 PM",
  },

  {
    id: "d15",
    name: "Mangia Nashville",
    category: "Fine Dining",
    image: "🍝",
    rating: 4.9,
    dietaryTags: ["gluten-free"],
    address: "701 Craighead St, Berry Hill, TN",
    description: "Italian restaurant with nearly every dish available gluten-free, including dedicated preparation areas and fryer for gluten-free meals.",
    hours: "Fri-Sat (Reservations Required)",
  },

  {
    id: "d16",
    name: "Sunflower Cafe",
    category: "Casual",
    image: "🥗",
    rating: 4.7,
    dietaryTags: ["vegan", "gluten-free"],
    address: "2834 Azalea Pl, Nashville, TN",
    description: "Plant-based cafe with extensive gluten-free menu including wraps, burgers, salads, and house-made gluten-free buns.",
    hours: "Daily",
  },

  {
    id: "d17",
    name: "bartaco",
    category: "Casual",
    image: "🌮",
    rating: 4.7,
    dietaryTags: ["gluten-free"],
    address: "12 South & East Nashville",
    description: "Large gluten-free menu using corn tortillas. Dedicated gluten-free fryer available when staff are notified of an allergy.",
    hours: "Daily",
  },

  {
    id: "d18",
    name: "CAVA",
    category: "Casual",
    image: "🥙",
    rating: 4.6,
    dietaryTags: ["gluten-free", "vegetarian", "vegan"],
    address: "Multiple Nashville locations",
    description: "Mediterranean bowls and salads with many naturally gluten-free ingredients. Staff can accommodate allergen requests.",
    hours: "Daily",
  },

  {
    id: "d19",
    name: "True Food Kitchen",
    category: "Casual",
    image: "🥗",
    rating: 4.6,
    dietaryTags: ["gluten-free", "vegetarian", "vegan"],
    address: "Green Hills, Nashville, TN",
    description: "Health-focused restaurant with numerous gluten-free menu items and allergy-aware preparation practices.",
    hours: "Daily",
  },

  {
    id: "d20",
    name: "Adi Rose Bakery",
    category: "Bakeries",
    image: "🎂",
    rating: 5.0,
    dietaryTags: ["vegan", "dairy-free", "egg-free", "gluten-free", "nut-free"],
    address: "Nashville, TN",
    description: "Custom allergy-friendly bakery specializing in vegan cakes that can also be made gluten-free, nut-free, soy-free, sesame-free, and free of other allergens upon request.",
    hours: "Custom Orders",
  },
];
